export const CATEGORY_LIST = [
  { label: "회의 진행", value: "meeting_leading" },
  { label: "의견 제시", value: "expressing_opinions" },
  { label: "프레젠테이션", value: "presentation" },
  { label: "이메일 작성", value: "email_writing" },
  { label: "전화 통화", value: "phone_call" },
  { label: "협상 및 계약", value: "negotiation_contract" },
  { label: "보고 및 요약", value: "reporting_summarizing" },
  { label: "네트워킹", value: "networking" },
  { label: "고객 응대", value: "customer_service" },
  { label: "면접", value: "interview" },
  { label: "IT / 기술", value: "it_technology" },
  { label: "금융 / 투자", value: "finance_investment" },
  { label: "마케팅 / 광고", value: "marketing_advertising" },
  { label: "영업 / 판매", value: "sales_commerce" },
  { label: "인사 / HR", value: "human_resources" },
  { label: "제조 / 생산", value: "manufacturing_production" },
  { label: "의료 / 제약", value: "medical_pharmaceutical" },
  { label: "교육", value: "education" },
  { label: "서비스 / 요식업", value: "service_hospitality" },
  { label: "미디어 / 엔터테인먼트", value: "media_entertainment" },
  { label: "일상생활", value: "daily_life" },
  { label: "기타", value: "etc" },
];
